version: '3.7'

networks:
  front-tier:
  back-tier:

services:

  prometheus:
    image: prom/prometheus
    user: "1000:1000"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - /home/robert/docker/server_monitoring/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always
  
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
        - 9100:9100
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global

  grafana:
    image: grafana/grafana
    user: "1000:1000"
    volumes:
      - /home/robert/docker/server_monitoring/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - back-tier
      - front-tier
    restart: always
    environment:
      GF_RENDERING_SERVER_URL: http://rpn-home-server:8081/render
      GF_RENDERING_CALLBACK_URL: http://rpn-home-server:3000/
      GF_LOG_FILTERS: rendering:debug

  renderer:
    image: grafana/grafana-image-renderer:latest
    networks:
      - back-tier
    ports:
      - 8081:8081
    restart: always
    environment:
      ENABLE_METRICS: 'true'
    depends_on:
      - grafana

volumes:
  grafana_data: {}
    